# Generated by Django 5.1.1 on 2025-08-06 04:34

import django.db.models.deletion
from django.db import migrations, models


def create_default_super_category(apps, schema_editor):
    ProductSuperCategory = apps.get_model('api', 'ProductSuperCategory')
    ProductCategory = apps.get_model('api', 'ProductCategory')
    
    # Create a default super category
    default_super = ProductSuperCategory.objects.create(
        name='General',
        description='General product category',
        enable=True
    )
    
    # Update all existing categories to use the default super category
    ProductCategory.objects.all().update(super_category=default_super)


def reverse_create_default_super_category(apps, schema_editor):
    ProductSuperCategory = apps.get_model('api', 'ProductSuperCategory')
    ProductSuperCategory.objects.filter(name='General').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productcategory_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='super_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.productsupercategory'),
        ),
        migrations.RunPython(create_default_super_category, reverse_create_default_super_category),
        migrations.AlterField(
            model_name='productcategory',
            name='super_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.productsupercategory'),
        ),
    ]
