# Generated by Django 5.1.1 on 2025-08-06 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productsupercategory_productcategory_super_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='super_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.productsupercategory'),
        ),
    ]
