# Generated by Django 5.1.1 on 2025-08-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productcategory_super_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsupercategory',
            name='enable',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
