# Generated by Django 5.1.1 on 2025-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/')),
                ('location', models.CharField(choices=[('HN', 'Ha Noi'), ('HUE', 'Hue'), ('HP', 'Hai Phong'), ('DN', 'Da Nang'), ('CT', 'Can Tho'), ('HCM', 'Ho Chi Minh'), ('CB', 'Cao Bang'), ('LS', 'Lang Son'), ('LC', 'Lai Chau'), ('DB', 'Dien Bien'), ('SL', 'Son La'), ('TH', 'Thanh Hoa'), ('NA', 'Nghe An'), ('HT', 'Ha Tinh'), ('QN', 'Quang Ninh'), ('TQ', 'Tuyen Quang'), ('LCI', 'Lao Cai'), ('TN', 'Thai Nguyen'), ('PT', 'Phu Tho'), ('BN', 'Bac Ninh'), ('HY', 'Hung Yen'), ('NB', 'Ninh Binh'), ('QT', 'Quang Tri'), ('QNG', 'Quang Ngai'), ('GL', 'Gia Lai'), ('KH', 'Khanh Hoa'), ('LD', 'Lam Dong'), ('DK', 'Dak Lak'), ('DNAI', 'Dong Nai'), ('TNIN', 'Tay Ninh'), ('VL', 'Vinh Long'), ('DT', 'Dong Thap'), ('CM', 'Ca Mau'), ('AG', 'An Giang')], default='HN', max_length=100)),
            ],
        ),
    ]
