# Generated by Django 5.1.1 on 2025-08-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_storestaff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storestaff',
            unique_together={('user', 'store')},
        ),
    ]
