# Generated by Django 5.1.1 on 2025-08-15 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_storestaff_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='staff_users',
            field=models.ManyToManyField(related_name='stores', through='api.StoreStaff', to=settings.AUTH_USER_MODEL),
        ),
    ]
