# Message codes for API responses
class MessageCodes:
    # Success messages
    OK = "OK"
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    DELETED = "DELETED"
    
    # Authentication messages
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    BLOCKED_USER = "BLOCKED_USER"
    INACTIVE_USER = "INACTIVE_USER"
    
    # Error messages
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    SERVER_ERROR = "SERVER_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    
    # User related messages
    USER_REGISTERED = "USER_REGISTERED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_ACTIVATED = "USER_ACTIVATED"
    EMAIL_EXISTS = "EMAIL_EXISTS"
    USERNAME_EXISTS = "USERNAME_EXISTS"
    
    # Product related messages
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    
    # Order related messages
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_UPDATED = "ORDER_UPDATED"
    ORDER_DELETED = "ORDER_DELETED"
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    
    # Category related messages
    CATEGORY_CREATED = "CATEGORY_CREATED"
    CATEGORY_UPDATED = "CATEGORY_UPDATED"
    CATEGORY_DELETED = "CATEGORY_DELETED"
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND" 